<?php

$CALENDARIO = [
  "insegnanti"=>[
    [
      "nome"=>"Beppi",
      "cognome"=>"Della Costa",
      "materia"=>[
        "nome"=>"matematica",
        "codice"=>"PPOA",
        "classe"=>[
          "1"=>[
            "reti"=>[
              "punteggio"=>0,
              "ore"=>5
            ],
            "multi"=>[
              "punteggio"=>0,
              "ore"=>7
            ]
          ],
          "2"=>[
            "reti"=>[
              "punteggio"=>0,
              "ore"=>6
            ]
          ],
          "multi"=>[
            "punteggio"=>0,
            "ore"=>7
          ]
        ],
        "3"=>[
          "reti"=>[
            "punteggio"=>0,
            "ore"=>6
          ],
          "multi"=>[
            "punteggio"=>0,
            "ore"=>7
          ]
        ],
        "4"=>[
          "reti"=>[
            "punteggio"=>0,
            "ore"=>6
          ],
          "multi"=>[
            "punteggio"=>0,
            "ore"=>7
          ]
        ]
      ],
      "assenze"=>[
        "data"=>[
          [
            "inizio"=>"13/10/1999",
            "fine"=>"12/10/1999"
          ],
          [
            "inizio"=>"12/11/1999",
            "fine"=>"13/11/1999"
          ]
        ]
      ],
      "preferenze"=>[
        "ore"=>[
          "classe"=>[
            "1"=>1,
            "2"=>2,
            "3"=>3,
            "4"=>2
          ]
        ],
        /* giorno della settimana in cui il prof è a casa */
        "giorni"=>[
          [
            "giovedì"
          ]
        ]
      ]
    ],
    "festivi"=>[
      "data"=>[
        [
          "inizio"=>"10/12/1999",
          "fine"=>"12/12/2000"
        ]
      ],
      "giorni"=>[
        "riposo"=>["sabato","domenica"]
      ]
    ],
    "rientro"=>[
      "classe"=>[
        "1"=>[
          "reti"=>[
            "giorni"=>["mercoledì"],
            "ore"=>8,
            "data"=>[
              "inizio"=>"2016/12/24",
              "fine"=>"2017/05/12"
            ]
          ],
          "multi"=>[
            "giorni"=>["mercoledì"],
            "ore"=>8,
            "data"=>[
              "inizio"=>"2016/12/24",
              "fine"=>"2017/05/12"
            ]
          ]
        ],
        "2"=>[
          "reti"=>[
            "giorni"=>["mercoledì"],
            "ore"=>8,
            "data"=>[
              "inizio"=>"2016/12/24",
              "fine"=>"2017/05/12"
            ]
          ],
          "multi"=>[
            "giorni"=>["mercoledì"],
            "ore"=>8,
            "data"=>[
              "inizio"=>"2016/12/24",
              "fine"=>"2017/05/12"
            ]
          ]
        ],
        "3"=>[
          "reti"=>[
            "giorni"=>["mercoledì"],
            "ore"=>8,
            "data"=>[
              "inizio"=>"2016/12/24",
              "fine"=>"2017/05/12"
            ]
          ],
          "multi"=>[
            "giorni"=>["mercoledì"],
            "ore"=>8,
            "data"=>[
              "inizio"=>"2016/12/24",
              "fine"=>"2017/05/12"
            ]
          ]
        ],
        "4"=>[
          "reti"=>[
            "giorni"=>["mercoledì"],
            "ore"=>8,
            "data"=>[
              "inizio"=>"2016/12/24",
              "fine"=>"2017/05/12"
            ]
          ],
          "multi"=>[
            "giorni"=>["mercoledì"],
            "ore"=>8,
            "data"=>[
              "inizio"=>"2016/12/24",
              "fine"=>"2017/05/12"
            ]
          ]
        ]
      ]
    ],
    "date_scuola"=>[
      "classe"=>[
        "1"=>[
          "reti"=>[
            "inizio"=>"2016/8/14",
            "fine"=>"2017/6/1"
          ],
          "multi"=>[
            "inizio"=>"2016/8/14",
            "fine"=>"2017/6/1"
          ]
        ],
        "2"=>[
          "reti"=>[
            "inizio"=>"2016/8/14",
            "fine"=>"2017/6/1"
          ],
          "multi"=>[
            "inizio"=>"2016/8/14",
            "fine"=>"2017/6/1"
          ]
        ],
        "3"=>[
          "reti"=>[
            "inizio"=>"2016/8/14",
            "fine"=>"2017/6/1"
          ],
          "multi"=>[
            "inizio"=>"2016/8/14",
            "fine"=>"2017/6/1"
          ]
        ],
        "4"=>[
          "reti"=>[
            "inizio"=>"2016/8/14",
            "fine"=>"2017/6/1"
          ],
          "multi"=>[
            "inizio"=>"2016/8/14",
            "fine"=>"2017/6/1"
          ]
        ]
      ]
    ],
    "nr_classi"=>4,
    "orario"=>[
      "lezioni"=>[
        "8.15",
        "9.15",
        "10.15",
        "11.15", // merenda
        "11.25",
        "12.25",
        "13.25", // rientro
        "14.15",
        "15.15",
        "16.15",
        "17.15"
      ]
    ]
    ]
  ];
