<?php

$CALENDARIO = [
  "insegnanti"=>[
    [
      "nome"=>"Beppi",
      "cognome"=>"Della Costa",
      "materia"=>[
        "nome"=>"matematica",
        "codice"=>"PPOA",
        "classe"=>[
          "1"=>[
            "reti"=>[
              "ore"=>6
            ],
            "multi"=>[
              "ore"=>20
            ]
          ],
          "2"=>[
            "reti"=>[
              "ore"=>40
            ],
          "multi"=>[
            "ore"=>0
          ]
        ],
        "3"=>[
          "reti"=>[
            "ore"=>60
          ],
          "multi"=>[
            "ore"=>60
          ]
        ],
        "4"=>[
          "reti"=>[
            "ore"=>60
          ],
          "multi"=>[
            "ore"=>40
          ]
        ]
        ],
        "preferenze"=>[
          "ore"=>[
            "classe"=>[
              "1"=>1,
              "2"=>2,
              "3"=>3,
              "4"=>2
            ]
          ],
          /* giorno della settimana in cui il prof è a casa */
          "giorni"=>[
            [
              "giovedì"
            ]
          ]
        ]
      ],
      "assenze"=>[
        "data"=>[
          [
            "inizio"=>"2016/10/14",
            "fine"=>"2016/12/14"
          ]
        ]
      ]
    ],
    [
      "nome"=>"Secondo",
      "cognome"=>"Festa",
      "materia"=>[
        "nome"=>"matematica",
        "codice"=>"PPOA",
        "classe"=>[
          "1"=>[
            "reti"=>[
              "ore"=>2
            ],
            "multi"=>[
              "ore"=>20
            ]
          ],
          "2"=>[
            "reti"=>[
              "ore"=>90
            ],
          "multi"=>[
            "ore"=>10
          ]
        ],
        "3"=>[
          "reti"=>[
            "ore"=>200
          ],
          "multi"=>[
            "ore"=>20
          ]
        ],
        "4"=>[
          "reti"=>[
            "ore"=>10
          ],
          "multi"=>[
            "ore"=>10
          ]
        ]
        ],
        "preferenze"=>[
          "ore"=>[
            "classe"=>[
              "1"=>1,
              "2"=>2,
              "3"=>3,
              "4"=>2
            ]
          ],
          /* giorno della settimana in cui il prof è a casa */
          "giorni"=>[
            [
              "giovedì", "venerdì", "martedì"
            ]
          ]
        ]
      ],
      "assenze"=>[
        "data"=>[
          [
            "inizio"=>"2016/11/14",
            "fine"=>"2016/12/14"
          ]
        ]
      ]
    ]
  ],
  "festivi"=>[
    "data"=>[
      [
        "inizio"=>"2016/8/14",
        "fine"=>"2016/8/17"
      ]
    ],
    "giorni"=>[
      "riposo"=>["sabato","domenica"]
    ]
  ],
  "rientro"=>[
    "classe"=>[
      "1"=>[
        "reti"=>[
          "giorni"=>["mercoledì"],
          "ore"=>8,
          "data"=>[
            "inizio"=>"2016/12/24",
            "fine"=>"2017/05/12"
          ]
        ],
        "multi"=>[
          "giorni"=>["mercoledì"],
          "ore"=>8,
          "data"=>[
            "inizio"=>"2016/12/24",
            "fine"=>"2017/05/12"
          ]
        ]
      ],
      "2"=>[
        "reti"=>[
          "giorni"=>["mercoledì"],
          "ore"=>8,
          "data"=>[
            "inizio"=>"2016/12/24",
            "fine"=>"2017/05/12"
          ]
        ],
        "multi"=>[
          "giorni"=>["mercoledì"],
          "ore"=>8,
          "data"=>[
            "inizio"=>"2016/12/24",
            "fine"=>"2017/05/12"
          ]
        ]
      ],
      "3"=>[
        "reti"=>[
          "giorni"=>["mercoledì"],
          "ore"=>8,
          "data"=>[
            "inizio"=>"2016/12/24",
            "fine"=>"2017/05/12"
          ]
        ],
        "multi"=>[
          "giorni"=>["mercoledì"],
          "ore"=>8,
          "data"=>[
            "inizio"=>"2016/12/24",
            "fine"=>"2017/05/12"
          ]
        ]
      ],
      "4"=>[
        "reti"=>[
          "giorni"=>["mercoledì"],
          "ore"=>8,
          "data"=>[
            "inizio"=>"2016/12/24",
            "fine"=>"2017/05/12"
          ]
        ],
        "multi"=>[
          "giorni"=>["mercoledì"],
          "ore"=>8,
          "data"=>[
            "inizio"=>"2016/12/24",
            "fine"=>"2017/05/12"
          ]
        ]
      ]
    ]
  ],
  "orari_scuola"=>[
    "classe"=>[
      "1"=>[
        "reti"=>[
          "ore_annuali"=>990,
          "inizio"=>"2016/8/14",
          "fine"=>"2017/6/1"
        ],
        "multi"=>[
          "ore_annuali"=>990,
          "inizio"=>"2016/8/14",
          "fine"=>"2017/6/1"
        ]
      ],
      "2"=>[
        "reti"=>[
          "ore_annuali"=>990,
          "inizio"=>"2016/8/14",
          "fine"=>"2017/6/1"
        ],
        "multi"=>[
          "ore_annuali"=>990,
          "inizio"=>"2016/8/14",
          "fine"=>"2017/6/1"
        ]
      ],
      "3"=>[
        "reti"=>[
          "ore_annuali"=>990,
          "inizio"=>"2016/8/14",
          "fine"=>"2017/6/1"
        ],
        "multi"=>[
          "ore_annuali"=>990,
          "inizio"=>"2016/8/14",
          "fine"=>"2017/6/1"
        ]
      ],
      "4"=>[
        "reti"=>[
          "ore_annuali"=>990,
          "inizio"=>"2016/8/14",
          "fine"=>"2017/6/1"
        ],
        "multi"=>[
          "ore_annuali"=>990,
          "inizio"=>"2016/8/14",
          "fine"=>"2017/6/1"
        ]
      ]
    ],
    "orario"=>[
      "lezioni"=>[
        "8.15",
        "9.15",
        "10.15",
        "11.15", // merenda
        "11.25",
        "12.25",
        "13.25", // rientro
        "14.15",
        "15.15",
        "16.15",
        "17.15"
      ]
    ]
  ],
  "nr_classi"=>4,

];
